<?php
$link=mysqli_connect('127.0.0.1','root','');
if(mysql_errno()){
	die('数据库连接错误'.mysql_error());
}
if(!mysqli_select_db($link,"school")){
	die('选择数据库错误'.mysql_error());
}
mysqli_set_charset($link,'utf8');
?>